sudo: false

language: go

go:
  - 1.13.x

install:
  - go get ./...

script:
  - go test -race -coverprofile=cp.out ./...

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash) -f cp.out
